FROM python:3.9-slim
RUN apt-get update && apt-get install -y --no-install-recommends git gcc && \
    rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY functions/to-spotify/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY functions/to-spotify/ .
COPY scripts/loop.sh /app/loop.sh
CMD ["/app/loop.sh", "python", "main.py"]
