FROM golang:1.21 AS build
WORKDIR /build
COPY functions/sort-playlists/go.mod functions/sort-playlists/go.sum ./
RUN go mod download
COPY functions/sort-playlists/*.go ./
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /sort-playlists

FROM alpine:3.19
COPY --from=build /sort-playlists /app/sort-playlists
CMD ["/app/sort-playlists"]
