FROM public.ecr.aws/lambda/python:3.12

# Install the function's dependencies
COPY requirements.txt .
RUN dnf install git gcc -y && pip install -r requirements.txt -t ./env

# Copy function code
COPY . ${LAMBDA_TASK_ROOT}

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "main.handle" ]
