apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: from-discogs-secrets
  namespace: mirrorfm
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: from-discogs-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: homeplane/from-discogs
