apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: manage-playlists-secrets
  namespace: mirrorfm
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: manage-playlists-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /homeplane/manage-playlists
