apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sort-playlists-secrets
  namespace: mirrorfm
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: sort-playlists-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: homeplane/sort-playlists
