apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: to-spotify-secrets
  namespace: mirrorfm
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: to-spotify-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /homeplane/to-spotify
